/** @type {import("prettier").Config} */
export default {
	arrowParens: 'always',
	endOfLine: 'lf',
	jsxSingleQuote: true,
	overrides: [
		{
			files: ['.*', '*.md', '*.toml', '*.yml'],
			options: {
				useTabs: false,
			},
		},
		{
			files: ['**/*.astro'],
			options: {
				parser: 'astro',
			},
		},
	],
	plugins: ['prettier-plugin-astro', '@pandabox/prettier-plugin'],
	printWidth: 80,
	semi: true,
	singleQuote: true,
	tabWidth: 2,
	trailingComma: 'all',
	useTabs: true,
	pandaLastProps: [],
	pandaStylePropsFirst: true,
	pandaSortOtherProps: true,
	pandaGroupOrder: [
		'System',
		'Container',
		'Display',
		'Visibility',
		'Position',
		'Transform',
		'Flex Layout',
		'Grid Layout',
		'Layout',
		'Border',
		'Border Radius',
		'Width',
		'Height',
		'Margin',
		'Padding',
		'Color',
		'Typography',
		'Background',
		'Shadow',
		'Table',
		'List',
		'Scroll',
		'Interactivity',
		'Transition',
		'Effect',
		'Other',
		'Conditions',
		'Arbitrary conditions',
		'Css',
	],
};
